### PR TITLE
Added Local Port setting to prefs

### PR DESCRIPTION
**Pull request by ghost**
Default is still port 9050, but now the users can see/change port number within the General tab.  I didn't bother to add this option to the "first run" screen since I figure most people wont need the option.  Also, didn't want to clutter the screen.

### CODE REVIEW

**Comment by chetan51** [comment]
Awesome, everything looks great. Do you think you could also add an option to enable / disable Growl notifications in the General tab, enabled by default? I think that's important to have before we release an update with Growl support.

Also, does the text on the preferences window look really weird to you, like it's aliased and not very smooth? Or is it just me?

**Comment by ghost** [comment]
Growl can be be disabled by app within the Growl control panel.  Do you want to add disable feature to Sidestep as well?

Yeah, the text does look rough.  I figured it was just me :)  Not sure what's causing that.

**Comment by chetan51** [comment]
Yeah, usually if an app posts Growl notifications, it has an in-app preference to disable it as well.

Hmm, I think the rough text was introduced in one of your commits, since the latest release doesn't have it. Weird.

**Comment by ghost** [comment]
I'll look into Growl and the rough text.  I'm not sure how to do make the text look like that even if I wanted to...

**Comment by ghost** [comment]
Looks like the aliasing issue has something to do with the tab.  If you expand the window and drag the text from the tab it looks fine.  I'll keep looking.

**Comment by chetan51** [comment]
Okay, good luck.

**Comment by ghost** [comment]
Got it!  One of the views was checked which acted like a layer over the text.  I committed the changes already, but I'll push once I have the Growl enable/disable option in place.

**Comment by chetan51** [comment]
Great!

Also, do you have any idea why it's not working for OS 10.5.8 (it just says "You cannot use this version of the application Sidestep.app with this version of Mac OS X").

**Comment by ghost** [comment]
Not sure.  I can get my old mac out of storage and try it.  That might take me a couple of days though.

**Comment by chetan51** [comment]
Whenever you can, I would appreciate it. I don't have any friends with 10.5.8, so I can't test it out myself. It's too bad that Sidestep doesn't work for users with 10.5.8 right now, and if we can eventually fix it, that would be great.

**Comment by ghost** [comment]
I got the code working on 10.5.8.  Your branch still uses NSApplicationDelegate.  That's a new protocol for 10.6 apparently.  I replaced that call when working on Growl.  If you build for 10.5 with my updated code, you can run the app under 10.5 and 10.6.  No need for two separate builds.

**Comment by chetan51** [comment]
Awesome! I just released the latest version will all your updates. Thanks a lot!

**Pull request merged**
